config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks"
 }

  root "welcome#index"
  get '/contact' => 'welcome#contact', :as => "contact"
  namespace :admin do
    resources :products
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get 'men'
      get 'women'
      get 'kids'
      get 'categories'
      get 'brands'
      post 'sort'
      post 'modify_display_quantity'
      post 'search'
    end
  end
  post 'prodcuts' => 'products#index'

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :photos

  resources :orders do
    member do
      get :pay_with_credit_card
     post :pay2go_atm_complete
     post :pay2go_cc_notify
    end
  end

  resources :items, controller: "cart_items"

  namespace :account do
    resources :orders
  end

  if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to admin_brands_path
    else
      render :new
    end
  end
  def index
    @brands = Brand.all
  end

  def edit
    @brand = Brand.find(params[:id])

  end
  def update
    @brand = Brand.find(params[:id])

    if @brand.update(brand_params)
      redirect_to admin_brands_path
    else
      render :edit
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

  end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/edit.html.erb
<h2>修改品牌</h2>
<%= simple_form_for [:admin, @brand] do |f| %>
	<div class="group">
	  <%= f.input :name %>
	</div>
	<%= f.submit "Update", :class =>"btn btn-primary", data: {disable_with: "Submitting.."} %>
<% end %>

app/views/admin/brands/index.html.erb
<h2> 品牌列表 </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增品牌", new_admin_brand_path, class: "btn btn-primary btn-sm") %>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Brands</div>
	<div class="panel-body"></div>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
        <th>Options</th>
			</tr>
		</thead>
		<tbody>
			<% @brands.each do |c| %>
				<tr>
					<td><%= c.id %></td>
					<td><%= c.name %></td>
					<td><%= link_to("Edit", edit_admin_brand_path(c)) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/brands/new.html.erb
<h2>新增品牌</h2>
<%= simple_form_for [:admin, @brand] do |f| %>
	<div class="group">
	  <%= f.input :name %>
	</div>
	<%= f.submit "Submit", :class =>"btn btn-default", data: {disable_with: "Submitting.."} %>

<% end %>