config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks"
 }

  root "welcome#index"
  get '/contact' => 'welcome#contact', :as => "contact"
  namespace :admin do
    resources :products
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get 'men'
      get 'women'
      get 'kids'
      get 'categories'
      get 'brands'
      post 'sort'
      post 'modify_display_quantity'
      post 'search'
    end
  end
  post 'prodcuts' => 'products#index'

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :photos

  resources :orders do
    member do
      get :pay_with_credit_card
     post :pay2go_atm_complete
     post :pay2go_cc_notify
    end
  end

  resources :items, controller: "cart_items"

  namespace :account do
    resources :orders
  end

  if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items, source: :product

	def add_product_to_cart_multi(product,quant,size)
		ci = cart_items.build
		ci.product = product
		ci.quantity = quant
		ci.size = size
		ci.save
	end
	def add_product_to_cart(product)
		ci = cart_items.build
		ci.product = product
		ci.save
	end
	def total_price
		sum = 0

		cart_items.each do |cart_item|
			sum = sum + (cart_item.product.price * cart_item.quantity )
		end
		return sum
	end
	def clean!
		cart_items.destroy_all
	end
	def find_cart_item(product)
		cart_items.find_by(product_id: product)
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!, only: [:checkout]

	def checkout
		@order = current_user.orders.build
		@info = @order.build_info
	end
	def clean
		current_cart.clean!
		flash[:warning] = "已清空購物車"
		redirect_to carts_path
	end
end

app/helpers/carts_helper.rb
module CartsHelper
	def render_cart_total_price(cart)
		cart.total_price
	end
	def calculate_current_price(price,amount)
		price*amount
	end
end

app/views/carts/checkout.html.erb
<!--
<div class="container">
    <div class="check-out">
      <div class="row">
         <div class="col-md-12">

    <h2> 購物明細 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明細</th>
          <th>單價</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.items.each do |product| %>
          <tr>
            <td>
              <%= link_to(product.title, product_path(product)) %>
            </td>
            <td>
              <%= product.price %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        總計 <%= render_cart_total_price(current_cart) %> NTD
      </span>
    </div>

    <hr>

    <h2> 訂單資訊 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>

        <%= f.simple_fields_for :info do |c| %>

          <legend> 訂購人</legend>
          <div class="form-group col-lg-6">
            <%= c.input :billing_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :billing_address  %>
          </div>

          <legend> 收貨人</legend>
          <div class="form-group col-lg-6">
           <%= c.input :shipping_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :shipping_address  %>
          </div>
        <% end %>

        <div class="checkout">
          <%= f.submit "生成訂單", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

        </div>
      </div>
    </div>
  </div>
</div> -->


<section class="registration-area">
  <div class="row">
  <!-- Shipping & Shipment Block Starts -->
    <div class="col-sm-6 col-sm-offset-3">
    <!-- Taxes Block Starts -->
      <div class="panel panel-smart">
        <div class="panel-heading">
          <h3 class="panel-title">
            Shipping &amp; Taxes
          </h3>
        </div>
        <div class="panel-body">
        <!-- Form Starts -->
          <form class="form-horizontal" role="form">
            <div class="form-group">
              <label for="inputCountry" class="col-sm-3 control-label">Country :</label>
              <div class="col-sm-9">
                <select class="form-control" id="inputCountry">
                  <option>- All Countries -</option>
                  <option>India</option>
                  <option>USA</option>
                  <option>UK</option>
                  <option>China</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="inputRegion" class="col-sm-3 control-label">Region :</label>
              <div class="col-sm-9">
                <select class="form-control" id="inputRegion">
                  <option>- All Regions -</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="inputZipCode" class="col-sm-3 control-label">Zip Code :</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" id="inputZipCode" placeholder="Zip Code">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">
                  Get Info
                </button>
              </div>
            </div>
          </form>
        <!-- Form Ends -->
        </div>
      </div>
    <!-- Taxes Block Ends -->
    <!-- Shipment Information Block Starts -->
      <div class="panel panel-smart">
        <div class="panel-heading">
          <h3 class="panel-title">
            Shipment Information
          </h3>
        </div>
        <div class="panel-body">
          <form class="form-horizontal" role="form">

            <%= simple_form_for @order do |f| %>

              <%= f.simple_fields_for :info do |c| %>
                <div class="form-group">
                  <label for="inputFname" class="col-sm-3 control-label">訂購人姓名:</label>
                  <div class="col-sm-9">
                    <%= c.input :billing_name  %>
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputFname" class="col-sm-3 control-label">訂購人地址:</label>
                  <div class="col-sm-9">
                    <%= c.input :billing_address  %>
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputFname" class="col-sm-3 control-label">收件人姓名:</label>
                  <div class="col-sm-9">
                    <%= c.input :shipping_name  %>
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputFname" class="col-sm-3 control-label">收件人地址:</label>
                  <div class="col-sm-9">
                    <%= c.input :shipping_address  %>
                  </div>
                </div>
              <% end %>
              <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                  <%= f.submit "生成訂單", class: "btn btn-warning",data: { disable_with: "Submitting..." } %>
                </div>
              </div>
            <% end %>
          </form>
        </div>
      </div>
    <!-- Shipment Information Block Ends -->
    </div>
  <!-- Shipping & Shipment Block Ends -->
  </div>
</section>

app/views/carts/index.html.erb
<div id="main-container" class="container">

  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li class="active">Shopping Cart</li>
  </ol>
  <h2 class="main-heading text-center">
    Shopping Cart
  </h2>
  <div class="table-responsive shopping-cart-table">
    <%= link_to(clean_carts_path ,method: :delete , class: "btn btn-danger pull-right", data: { confirm: "你確定要清空整個購物車嗎？"} ) do %>
      清空購物車<i class="fa fa-trash"></i>
    <% end %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <td class="text-center">
            Image
          </td>
          <td class="text-center">
            Product Details
          </td>
          <td class="text-center">
            Options
          </td>
          <td class="text-center">
            Price
          </td>
          <td class="text-center">
            Total
          </td>
          <td class="text-center">
            Action
          </td>
        </tr>
      </thead>
      <tbody>
        <% current_cart.items.each do |product| %>
            <tr>
              <td class="text-center">
                <%= link_to product_path(product) do %>
                  <%= get_photo(product.photos) %>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to(product.title ,product_path(product)) %>
              </td>
              <td class="text-center">
                <div class="input-group btn-block">
                  <!-- <input type="text" name="quantity" value="1" size="1" class="form-control" /> -->
                  <% item = current_cart.find_cart_item(product) %>
                    <%= form_for item, url: item_path(product) do |f| %>

                      <!-- <%= f.submit "",class: "btn btn-default tool-tip",type:"submit", title:"Update", data: {disable_with: "Submitting"} do %>
                        <i class="fa fa-refresh"></i>
                      <% end %> -->


                      <div class="col-md-10 inline-block">
                        <div class="group">
                          <%= f.label :quantity %>
                          <%= f.text_field :quantity, {class:"pull-right",value: item.quantity} %>
                        </div>
                        </br>
                        <div class="group">
                          <%= f.label :size %>
                          <%= f.select(:size, (36..47),{},{class:"form-control pull-right",value: item.size ,style:"width:170px" }) %>
                        </div>
                      </div>
                    </br>
                      <div class="col-md-2">
                        <div class="group">
                          <%= button_tag( :class => "btn btn-default tool-tip",title:"Update", data: {disable_with: "Submitting"}) do %>
                            <i class="fa fa-refresh"></i>
                          <% end %>
                        </div>
                      </div>
                    <% end %>

                </div>
              </td>
              <td class="text-center">
                $<%= product.price %>
              </td>
              <td class="text-center">
                $<%= calculate_current_price( product.price ,item.quantity ) %>
              </td>
              <td class="text-center">
                <%= button_to item_path(product), :class => "btn btn-default tool-tip", :data => { :title => 'Remove'}  ,:type => "button", :method=> :delete do %>
                  <i class="fa fa-times-circle"></i>
                <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="4" class="text-right">
          <strong>Total :</strong>
          </td>
          <td colspan="2" class="text-left">
          $<%= render_cart_total_price(current_cart) %>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
  <section class="registration-area">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-smart">
          <div class="panel-body">
              <dl class="dl-horizontal">
                  <dt>Payment Fee :</dt>
                  <dd>$10.00</dd>
                  <dt>Shipment Fee :</dt>
                  <dd>$15.00</dd>
              </dl><hr/>
              <dl class="dl-horizontal total">
                  <dt>Total :</dt>
                  <dd>$<%= render_cart_total_price(current_cart) %></dd>
              </dl><hr/>
              <div class="text-uppercase clearfix">
                <%= link_to(products_path, class: "btn btn-default pull-left") do %>
                  <span class="hidden-xs">Continue Shopping</span>
                  <span class="visible-xs">Continue</span>
                <% end %>
                  <!-- <a href="#" class="btn btn-default pull-left">
                      <span class="hidden-xs">Continue Shopping</span>
                      <span class="visible-xs">Continue</span>
                  </a> -->
                  <%= link_to("Checkout", checkout_carts_path, method: :post, class: "btn btn-default pull-right") %>
              </div>
          </div>
      </div>
    </div>
</section>