config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks"
 }

  root "welcome#index"
  get '/contact' => 'welcome#contact', :as => "contact"
  namespace :admin do
    resources :products
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get 'men'
      get 'women'
      get 'kids'
      get 'categories'
      get 'brands'
      post 'sort'
      post 'modify_display_quantity'
      post 'search'
    end
  end
  post 'prodcuts' => 'products#index'

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :photos

  resources :orders do
    member do
      get :pay_with_credit_card
     post :pay2go_atm_complete
     post :pay2go_cc_notify
    end
  end

  resources :items, controller: "cart_items"

  namespace :account do
    resources :orders
  end

  if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :photos , dependent: :destroy
	accepts_nested_attributes_for :photos
	belongs_to :category
	belongs_to :brand
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required
  def new
    @product = Product.new
    @photo = @product.photos.build
    @categories = Category.all
    @brands = Brand.all
    # @category = @product.build_category
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
    @brands = Brand.all
    @photo = @product.photos.all
    session[:product_id] = params[:id]
    # if @product.photos.present?
    #   @photo = @product.photo
    # else
    #   @photo = @product.build_photo
    # end
  end

  def update
    @product = Product.find(params[:id])
    # @category = params[:category_id]
    # @product.category_id = @category
    respond_to do |format|
      if @product.update(product_params)
        if @product.save
          params[:product][:photo][:image].each do |i|
            @photo = @product.photos.create!(:image => i)
          end
          format.html {redirect_to edit_admin_product_path(session[:product_id]), notice: 'Post was successfully updated.' }
        else
          # @categories = Category.all
          render :edit
        end
      else
        # @categories = Category.all
        render :edit
      end
    end
  end

  def create
    @product = Product.new(product_params)
    # @category = params[:category_id]
    # @product.category_id = @category

    respond_to do |format|
      if @product.save
        params[:product][:photo][:image].each do |i|
          @photo = @product.photos.create!(:image => i)
        end
        format.html {redirect_to admin_products_path, notice: 'Post was successfully created.' }
      else
        # @categories = Category.all
        render :new
      end
    end
  end

  def index
    @products = Product.includes(:photos).all
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :category_id, :brand_id, :gender, photos_attributes: [:id, :product_id, :image] )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # include ProductsHelper
  before_action :authenticate_user!, only: [:add_to_cart]
  def index_page
    @men = Product.where(:gender => 1).limit(5).order("id DESC")
    @women = Product.where(:gender => 2).limit(5).order("id DESC")
  end

  def index

    @title = 'Products'
    @products = Product.paginate(:page => params[:page], :per_page => 9)
    @products = @q.result.paginate(:page => params[:page], :per_page => 9)
    # if params[:search]
    #   @products = Product.all
    #   # @products = Product.where('title LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
    # else
    #   @products = Product.all
    # end

    # if params[:category].blank? && params[:brand].blank? && params[:gender].blank?
    #   @title = 'Products'
    #   @products = Product.paginate(:page => params[:page], :per_page => 9)
    #   @products = @q.result.paginate(:page => params[:page], :per_page => 9)
    # elsif params[:category]
    #   @title = params[:category]
    #   category_id = Category.find_by(name: params[:category]).id
    #   @products = Product.where(category_id: @category_id).paginate(:page => params[:page], :per_page => 9)
    # elsif params[:brand]
    #   @title = params[:brand]
    #   brand_id = Brand.find_by(name: params[:brand]).id
    #   @products = Product.where(brand_id: @brand_id).paginate(:page => params[:page], :per_page => 9)
    # elsif params[:gender]
    #   gender = params[:gender]
    #   @title = I18n.t("gender.#{gender}")
    #   @products = Product.where(gender: gender).paginate(:page => params[:page], :per_page => 9)
    # end
  end

  def search
    if params[:search]
      @products = Product.where('title LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 9).includes(:photos).all
    else
      @products = Product.all.paginate(:page => params[:page], :per_page => 9).includes(:photos).all
    end
  end

  def show
    if params[:search]
      @products = Product.where('title LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
    else
    	@product = Product.find(params[:id])
      Product.update_counters @product.id, :view_counts => 1
      @photo = @product.photos.all
      @category = Category.find_by(id: @product.category_id)
      @brand = Brand.find_by(id: @product.brand_id)
      @related_product = Product.where(gender: @product.gender).where.not(id: @product.id).order("RANDOM()").limit(4)
    end
  end

  def add_to_cart
  	@product = Product.find(params[:id])

  	if !current_cart.items.include?(@product)
      if params[:data].blank?
        current_cart.add_product_to_cart(@product)
      else
        q = params[:data][:quantity]
        sz = params[:data][:size]
    		current_cart.add_product_to_cart_multi(@product,q,sz)
      end
  		flash[:notice] = "你已成功將 #{@product.title}加入購物車 "
  	else
  		flash[:warning] = "你的購物車已有此物品"
  	end

  	redirect_to :back
  end

  def men
    @products = Product.where(gender: 1).paginate(:page => params[:page], :per_page => 9).includes(:photos).all
    @random = Product.order("RANDOM()").limit(1)
    params[:send_params] = @products
    session[:name] = 'gender'
    session[:s_id] = '1'
  end

  def women
    @products = Product.where(gender: 2).paginate(:page => params[:page], :per_page => 9).includes(:photos).all
    session[:name] = 'gender'
    session[:s_id] = '2'
  end
  def kids
    @products = Product.where(gender: 3).paginate(:page => params[:page], :per_page => 9).includes(:photos).all
    session[:name] = 'gender'
    session[:s_id] = '3'
  end
  def categories
    if params[:category]
      @title = params[:category]
      category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: category_id).paginate(:page => params[:page], :per_page => 9).includes(:photos).all
      session[:name] = 'category_id'
      session[:s_id] = category_id
    end
  end

  def brands
    @title = params[:brand]
    brand_id = Brand.find_by(name: params[:brand]).id
    @products = Product.where(brand_id: brand_id).paginate(:page => params[:page], :per_page => 9).includes(:photos).all
    session[:name] = 'brand_id'
    session[:s_id] = brand_id
  end
  def sort
    sortway = params[:sort]
    id = session[:s_id]
    page = (params[:per_page]? 9 : params[:per_page])
    @products = Product.where(session[:name] => id).order(params[:sort]).paginate(:page => params[:page], :per_page => page).includes(:photos).all
  end
  def modify_display_quantity
    id = session[:s_id]
    page = (params[:per_page] ? 3 : params[:per_page])
    @products = Product.where(session[:name] => id).paginate(:page => params[:page], :per_page => page).includes(:photos).all

  end

  # def modify
  #   if params[:per_page]?
  #     @products = Product.where(session[:name] => id).order(params[:sort]).paginate(:page => params[:page], :per_page => params[:per_page])
  #   end
  # end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def current_category(cate_id)
      @current_category ||= find_category(cate_id)
    end

    # def current_gender(gender)
    #   render=''
    #   if gender === 1
    #      render = 'MEN'
    #   else
    #      render = 'WOMEN'
    #   end
    #   render
    # end
    def find_category(cate_id)
      category = Category.find_by(id: cate_id).name
    end


end

app/views/admin/products/edit.html.erb
<h2>修改產品</h2>
<%= simple_form_for [:admin, @product] do |f| %>
<div class="group">
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :quantity %>
	<%= f.input :price %>
	<%= f.simple_fields_for :photo do |c| %>
		<%= c.input :image,:input_html => { :multiple => true },name: "photo[image][]", as: :file %>
	<% end %>

	<% @photo.each do |p| %>
		<%= image_tag p.image.thumb.url %>
		<%= link_to photo_path(p.id), method: :delete, data: { confirm: "Do you want destroy this prokect?"} do %>
			<i class="fa fa-trash"></i>
		<% end %>
		<%= link_to "Edit Photo" , edit_photo_path(p) %>
	<% end %>

	<%= f.input :category_id, collection: @categories, prompt: 'Choose one' %>
	<%= f.input :brand_id, collection: @brands, prompt: 'Choose Brand' %>
	<%= f.input :gender, collection: [['Men', 1], ['Women', 2]], prompt: 'Choose Gender' %>
</div>

	<%= f.submit "Update", :class =>"btn btn-primary", data: {disable_with: "Submitting.."} %>

<% end %>

app/views/admin/products/index.html.erb
<h2> Admin </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Products</div>
	<div class="panel-body"></div>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>#</th>
				<th width="220">Product Pic</th>
				<th>Name</th>
				<th>Price</th>
				<th width="100">Options</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.id %></td>
					<td>
            <%= link_to edit_admin_product_path(product) do %>
              <%= get_photo(product.photos) %>
            <% end %>
		      </td>
					<td><%= product.title %></td>
					<td>$<%= product.price %></td>
					<td><%= link_to("Edit", edit_admin_product_path(product)) %></td>
				</tr>

			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/products/new.html.erb
<h2>新增產品</h2>
<%= simple_form_for [:admin, @product], :html => { :multipart => true } do |f| %>
	<div class="group">
	  <%= f.input :title %>
	  <%= f.input :description %>
	  <%= f.input :quantity %>
	  <%= f.input :price %>
		<%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image,:input_html => { :multiple => true },name: "photo[][image]", as: :file %>
    <% end %>
		<%= f.input :category_id, collection: @categories, prompt: 'Choose one' %>
		<%= f.input :brand_id, collection: @brands, prompt: 'Choose Brand' %>
		<%= f.input :gender, collection: [['Men', 1], ['Women', 2]], prompt: 'Choose Gender' %>
	</div>
	<div class="group">
		<%= f.submit "Submit", :class =>"btn btn-default", data: {disable_with: "Submitting.."} %>
	</div>
<% end %>