config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks"
 }

  root "welcome#index"
  get '/contact' => 'welcome#contact', :as => "contact"
  namespace :admin do
    resources :products
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get 'men'
      get 'women'
      get 'kids'
      get 'categories'
      get 'brands'
      post 'sort'
      post 'modify_display_quantity'
      post 'search'
    end
  end
  post 'prodcuts' => 'products#index'

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :photos

  resources :orders do
    member do
      get :pay_with_credit_card
     post :pay2go_atm_complete
     post :pay2go_cc_notify
    end
  end

  resources :items, controller: "cart_items"

  namespace :account do
    resources :orders
  end

  if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

end

app/views/common/_cartlist.html.erb
<button type="button" data-toggle="dropdown" class="btn btn-block btn-lg dropdown-toggle">
  <i class="fa fa-shopping-cart"></i>
  <span class="hidden-md">Cart:</span>
  <span id="cart-total"><%= render_cart_items_count(current_cart) %> item(s) - $<%= render_cart_total_price(current_cart) %></span>
  <i class="fa fa-caret-down"></i>
</button>
<ul class="dropdown-menu pull-right">
  <li>
    <table class="table hcart">
      <% current_cart.items.each do |product| %>
        <tr>
          <td class="text-center">
            <%= link_to product_path(product) do %>
  						<%= get_photo(product.photos) %>
  					<% end %>
          </td>
          <% item = current_cart.find_cart_item(product) %>
          <td class="text-left">
            <%= link_to(product.title, product_path(product)) %>
          </td>
          <td class="text-right">
            x <%= item.quantity %>
          </td>
          <td class="text-right">
            $ <%= product.price %>
          </td>
          <td class="text-center">
            <%= link_to item_path(product), :data => { :title => 'Remove'} , :method=> :delete do %>
              <i class="fa fa-times"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </li>
  <li>
    <table class="table table-bordered total">
      <tbody>
        <tr>
          <td class="text-right"><strong>Tax</strong></td>
          <td class="text-left">$100</td>
        </tr>
        <tr>
          <td class="text-right"><strong>Total</strong></td>
          <td class="text-left">$<%= render_cart_total_price(current_cart) %></td>
        </tr>
      </tbody>
    </table>
    <p class="text-right btn-block1">
      <%= link_to "View Cart",carts_path %>
      <%= link_to("Checkout", checkout_carts_path, method: :post) %>
    </p>
  </li>
</ul>

app/views/common/_foot.html.erb
<footer id="footer-area">
<!-- Footer Links Starts -->
  <div class="footer-links">
    <div class="container">
      <div class="col-md-10 col-sm-12 col-sm-offset-1 last">
        <h4 class="lead">
          CHRISTIAN LOUBOUTIN: </br>
          <span>IT IS NOT MY JOB TO CREATE SOMETHING COMFORTABLE</span>
        </h4>
    </div>
    </div>

  <!-- Container Starts -->
    <!-- <div class="container">

        <div class="col-md-2 col-sm-6">
          <h5>Information</h5>
          <ul>
            <li><a href="about.html">About Us</a></li>
            <li><a href="#">Delivery Information</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms &amp; Conditions</a></li>
          </ul>
        </div>
        <div class="col-md-2 col-sm-6">
          <h5>My Account</h5>
          <ul>
            <li><a href="#">My orders</a></li>
            <li><a href="#">My merchandise returns</a></li>
            <li><a href="#">My credit slips</a></li>
            <li><a href="#">My addresses</a></li>
            <li><a href="#">My personal info</a></li>
          </ul>
        </div>
        <div class="col-md-2 col-sm-6">
          <h5>Service</h5>
          <ul>
            <li><a href="contact.html">Contact Us</a></li>
            <li><a href="#">Returns</a></li>
            <li><a href="#">Site Map</a></li>
            <li><a href="#">Affiliates</a></li>
            <li><a href="#">Specials</a></li>
          </ul>
        </div>
        <div class="col-md-2 col-sm-6">
          <h5>Follow Us</h5>
          <ul>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">RSS</a></li>
            <li><a href="#">YouTube</a></li>
          </ul>
        </div>
        <div class="col-md-4 col-sm-12 last">
          <h5>Contact Us</h5>
          <ul>
            <li>My Company</li>
            <li>
              1247 LB Nagar Road, Hyderabad, Telangana - 35
            </li>
            <li>
              Email: <a href="#">info@demolink.com</a>
            </li>
          </ul>
          <h4 class="lead">
            Tel: <span>1(234) 567-9842</span>
          </h4>
        </div> -->
      <!-- Contact Us Ends -->
    </div>
  <!-- Container Ends -->
  </div>
<!-- Footer Links Ends -->
<!-- Copyright Area Starts -->
  <div class="copyright">
  <!-- Container Starts -->
    <div class="container">
    <!-- Starts -->
      <p class="pull-left">
        &nbsp; Copyright © 2015 ShoeShop Template by. Designed By <a href="https://github.com/ponponwu">PonPon</a>
      </p>
    <!-- Ends -->
    <!-- Payment Gateway Links Starts -->
      <ul class="pull-right list-inline">
        <li>
          <%= image_tag("cirrus.png")%>
        </li>
        <li>
          <%= image_tag("paypal.png")%>
        </li>
        <li>
          <%= image_tag("visa.png")%>
        </li>
        <li>
          <%= image_tag("mastercard.png")%>
        </li>
        <li>
          <%= image_tag("americanexpress.png")%>
        </li>
      </ul>
    <!-- Payment Gateway Links Ends -->
    </div>
  <!-- Container Ends -->
  </div>
<!-- Copyright Area Ends -->
</footer>

app/views/common/_nav.html.erb
<div class="header">
    <div class="container">
        <div class="header-top">
            <div class="logo">
                <a href="/"><%= image_tag('logo.png') %></a>
            </div>
            <div class="top-nav">
              <span class="menu"><%= image_tag('menu.png') %></span>
                <ul class="icon1 sub-icon1">
                  <li >
                      <%= link_to("Home", root_path) %>
                  </li>
                  <li>
                    <%= link_to("Products", products_path) %>
                  </li>
                  <li>
          					<%= link_to carts_path do %>
          					購物車<i class="fa fa-shopping-cart"></i>
          					(<%= render_cart_items_count(current_cart) %>
          					)
          					<% end %>
          				</li>
                  <% if !user_signed_in? %>
            				<li><%= link_to("登入", new_user_session_path) %></li>
            				<li><%= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %></li>
            			<% else %>
            				<li class="dropdown">
            					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
            						<%= current_user.email %>
            						<b class="caret"></b>
            					</a>
            					<ul class="dropdown-menu">
            						<% if current_user.admin? %>
            						  <li><%= link_to("管理者介面", admin_products_path) %></li>
            						<% end %>
              						<li><%= link_to("個人訂單列表", account_orders_path )  %></li>
              					  <li><%= link_to("登出", destroy_user_session_path, method: :delete ) %></li>
            					</ul>
            				</li>
      				     <% end %>
                </ul>
              <!-- <ul class="icon1 sub-icon1">
                <li><a href="#"><i></i></a>
                <ul class="sub-icon1 list">
    						  <div class="shopping_cart">
    							  <div class="cart_box">
    							   	 <div class="message">
    												<div class="list_desc">
                              <li><h3><%= link_to("個人訂單列表", account_orders_path ) %></h3></li>
                              <% if !user_signed_in? %>
                        				<li><%= link_to("登入", new_user_session_path) %></li>
                        				<li><%= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %></li>
                        			<% else %>
                        				<li class="dropdown">
                        					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        						<%= current_user.email %>
                        						<b class="caret"></b>
                        					</a>
                        					<ul class="dropdown-menu">
                        						<% if current_user.admin? %>
                        						  <%= link_to("管理者介面", admin_products_path) %>
                        						<% end %>
                          						<li><%= link_to("個人訂單列表", account_orders_path )  %></li>
                          						<li><%= link_to("登出", destroy_user_session_path, method: :delete ) %></li>
                        					</ul>
                        				</li>
                  				     <% end %>


    												</div>
                          <div class="clearfix"></div>
                      </div>
                    </div>
                  </div>
    							  <div class="check_button"><a href="cart.html">View Cart</a></div>
    					      <div class="clearfix"></div>
    						</ul>
              </ul> -->
                <!--script-->
            </div>
            <!-- <div class="collapse navbar-collapse">
             <ul class="nav navbar-nav">
               <li class="active"><a href="#">Home</a></li>
               <li class="dropdown "><a href="#" id="drop1" data-toggle="dropdown" class="dropdown-toggle" role="button">About <b class="caret"></b></a>
                   <ul role="menu" class="dropdown-menu" aria-labelledby="drop1">
                       <li role="presentation"><a href="#" role="menuitem">Overview</a></li>
                       <li role="presentation"><a href="#" role="menuitem">Team Bios</a></li>
                       <li role="presentation"><a href="#" role="menuitem">Customers</a></li>
                       <li role="presentation"><a href="#" role="menuitem">Careers</a></li>
                   </ul>
               </li>
               <li><a href="#contact">Contact</a></li>
             </ul>
           </div> -->
            <div class="clearfix"></div>
        </div>
    </div>
</div>

app/views/common/_navb.html.erb
<!-- Header Section Starts -->
	<header id="header-area">
	<!-- Header Top Starts -->
		<div class="header-top">
			<div class="container">
				<!-- Header Links Starts -->
					<div class="col-sm-8 col-xs-12">
						<div class="header-links">
							<ul class="nav navbar-nav pull-left">
								<li>
									<a href="/">
										<i class="fa fa-home" title="Home"></i>
										<span class="hidden-sm hidden-xs">
											Home
										</span>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-heart" title="Wish List"></i>
										<span class="hidden-sm hidden-xs">
											Wish List(0)
										</span>
									</a>
								</li>
								<!-- <li>
									<a href="#">
										<i class="fa fa-user" title="My Account"></i>
										<span class="hidden-sm hidden-xs">
											My Account
										</span>
									</a>
								</li> -->
								<li>
                  <li>
          					<%= link_to carts_path do %>
          					  <i class="fa fa-shopping-cart" title="Shopping Cart"></i>
                      <span class="hidden-sm hidden-xs">
  											Shopping Cart
  										</span>
          					<% end %>
          				</li>
								</li>
								<!-- <li>
									<a href="#">
										<i class="fa fa-crosshairs" title="Checkout"></i>
										<span class="hidden-sm hidden-xs">
											Checkout
										</span>
									</a>
								</li> -->
								<!-- <li>
									<a href="register.html">
										<i class="fa fa-unlock" title="Register"></i>
										<span class="hidden-sm hidden-xs">
											Register
										</span>
									</a>
								</li> -->
								<% if !user_signed_in? %>
									<li>
										<%= link_to new_user_registration_path do %>
											<i class="fa fa-unlock" title="Register"></i>
											<span class="hidden-sm hidden-xs">
												Register
											</span>
										<% end %>
									</li>
	                <li>
	                  <%= link_to new_user_session_path do %>
	                    <i class="fa fa-lock" title="Login"></i>
	                    <span class="hidden-sm hidden-xs">
												Login
	                    </span>
	                  <% end %>
	                </li>
	                <li>
	                  <%= link_to user_omniauth_authorize_path(:facebook) do %>
	                    <i class="fa fa-lock" title="Login"></i>
	                    <span class="hidden-sm hidden-xs">
												Login With FaceBook
	                    </span>
	                  <% end %>
	                </li>
								<% else %>
									<% if current_user.admin? %>
										<li>
											<%= link_to admin_products_path do %>
												管理者介面<i class="fa fa-user" title="My Account"></i>
												<span class="hidden-sm hidden-xs">
												</span>
											<% end %>
										</li>
									<% end %>
										<li>
											<%= link_to account_orders_path do %>
												個人訂單列表<i class="fa fa-lock" title="Login"></i>
												<span class="hidden-sm hidden-xs">
												</span>
											<% end %>
										</li>
										<li>
											<%= link_to destroy_user_session_path, method: :delete do %>
												登出<i class="fa fa-lock" title="Login"></i>
												<span class="hidden-sm hidden-xs">
												</span>
											<% end %>
										</li>
								<% end %>
							</ul>
						</div>
					</div>
				<!-- Header Links Ends -->
				<!-- Currency & Languages Starts -->
					<div class="col-sm-4 col-xs-12">
						<!-- <div class="pull-right">
						<! Languages Starts >
							<div class="btn-group">
								<button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
									Eng
									<i class="fa fa-caret-down"></i>
								</button>
								<ul class="pull-right dropdown-menu">
									<li>
										<a tabindex="-1" href="#">English</a>
									</li>
									<li>
										<a tabindex="-1" href="#">French</a>
									</li>
								</ul>
							</div> -->
						<!-- Languages Ends -->
						<!-- Currency Starts -->
							<!-- <div class="btn-group">
								<button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
									$
									<i class="fa fa-caret-down"></i>
								</button>
								<ul class="pull-right dropdown-menu">
									<li><a tabindex="-1" href="#">Pound </a></li>
									<li><a tabindex="-1" href="#">US Dollar</a></li>
									<li><a tabindex="-1" href="#">Euro</a></li>
								</ul>
							</div> -->
						<!-- Currency Ends -->
						<!-- </div> -->
					</div>
				<!-- Currency & Languages Ends -->
			</div>
		</div><!--Header Top -->
	<!-- Header Top Ends -->
	<!-- Starts -->
		<div class="container">
		<!-- Main Header Starts -->
			<div class="main-header">
				<div class="row">
				<!-- Search Starts -->
					<div class="col-md-3">
						<div id="search">
							<div class="input-group">

								<!-- <%= search_form_for @q do |f| %>
			            <%= f.search_field :title_or_description_cont,:class =>'form-control input-lg',:type =>'text' %>
										<span class="input-group-btn">
					            <%= f.button :class => 'btn btn-lg',:type => 'button' do %>
												<i class="fa fa-search"></i>
											<% end %>
										</span>
			          <% end %> -->

							  <input type="text" class="form-control input-lg" id="input_search" placeholder="Search">
							  <span class="input-group-btn">
									<button class="btn btn-lg" id="btnSearch" type="button">
										<i class="fa fa-search"></i>
									</button>
							  </span>

							</div>
						</div>
					</div>
				<!-- Search Ends -->
				<!-- Logo Starts -->
					<div class="col-md-6">
						<div id="logo">
							<a href="/"><%= image_tag("shoepify.png" ,title: "Spice Shoppe" ,alt: "Spice Shoppe" ,class: "img-responsive") %></a>
						</div>
					</div>
				<!-- Logo Starts -->
				<!-- Shopping Cart Starts -->
					<div class="col-md-3">
						<div id="cart" class="btn-group btn-block">
							<%= render :partial => "common/cartlist" %>
						</div>
					</div>
				<!-- Shopping Cart Ends -->
				</div>
			</div>
		<!-- Main Header Ends -->
		<!-- Main Menu Starts -->
			<nav id="main-menu" class="navbar" role="navigation">
			<!-- Nav Header Starts -->
				<div class="navbar-header">
					<button type="button" class="btn btn-navbar navbar-toggle" data-toggle="collapse" data-target=".navbar-cat-collapse">
						<span class="sr-only">Toggle Navigation</span>
						<i class="fa fa-bars"></i>
					</button>
				</div>
			<!-- Nav Header Ends -->
			<!-- Navbar Cat collapse Starts -->
				<div class="collapse navbar-collapse navbar-cat-collapse">
					<ul class="nav navbar-nav">
						<li><%= link_to("Men", men_products_path) %></li>
						<li><%= link_to("Women", women_products_path) %></li>
						<li><%= link_to("Kids", kids_products_path) %></li>
						<!-- <li class="dropdown">
							<a href="category-list.html" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="10">Kids</a>
							<div class="dropdown-menu">
								<div class="dropdown-inner">
									<ul class="list-unstyled">
										<li class="dropdown-header">Sub Category</li>
										<li><a tabindex="-1" href="#">item 1</a></li>
										<li><a tabindex="-1" href="#">item 2</a></li>
										<li><a tabindex="-1" href="#">item 3</a></li>
									</ul>
									<ul class="list-unstyled">
										<li class="dropdown-header">Sub Category</li>
										<li><a tabindex="-1" href="#">item 1</a></li>
										<li><a tabindex="-1" href="#">item 2</a></li>
										<li><a tabindex="-1" href="#">item 3</a></li>
									</ul>
									<ul class="list-unstyled">
										<li class="dropdown-header">Sub Category</li>
										<li><a tabindex="-1" href="#">item 1</a></li>
										<li><a tabindex="-1" href="#">item 2</a></li>
										<li><a tabindex="-1" href="#">item 3</a></li>
									</ul>
								</div>
							</div>
						</li> -->
						<!-- <li><a href="category-list.html">Team Sports</a></li>
						<li><a href="category-list.html">Designer Shoes</a></li>
						<li><a href="category-list.html">Black Shoes</a></li>
						<li><a href="category-list.html">Flats</a></li> -->
						<!-- <li><a href="category-list.html">Buckles</a></li> -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="10">
                    Categories
                </a>
                <ul class="dropdown-menu" role="menu">
                  <% cache Category.order('updated_at DESC').last do %>
                    <% Category.find_each do |c| %>
                      <li><%= link_to(c.name,categories_products_path(category: c.name),tabindex: "-1" ) %></li>
                    <% end %>
                  <% end %>
                </ul>
            </li>
						<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="10">
                    Brands
                </a>
                <ul class="dropdown-menu" role="menu">
                  <% cache Brand.order('updated_at DESC').last do %>
                    <% Brand.find_each do |b| %>
                      <li><%= link_to(b.name,brands_products_path(brand: b.name),tabindex: "-1" ) %></li>
                    <% end %>
                  <% end %>
                </ul>
            </li>
						<li><a href="/contact">Conatact Us</a></li>
					</ul>
				</div>
			<!-- Navbar Cat collapse Ends -->
			</nav>
		<!-- Main Menu Ends -->
		</div>
	<!-- Ends -->
	</header>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a href="/" class="navbar-brand">ArtStore</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active">
					<%= link_to("Products", products_path) %>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to carts_path do %>
					購物車<i class="fa fa-shopping-cart"></i>
					(<%= render_cart_items_count(current_cart) %>
					)
					<% end %>
				</li>

				<% if !user_signed_in? %>
				<li><%= link_to("登入", new_user_session_path) %></li>
				<li><%= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %></li>
			<% else %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<%= current_user.email %>
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<% if current_user.admin? %>
						<li><%= link_to("管理者介面", admin_products_path) %></li>
						<% end %>
						<li><%= link_to("個人訂單列表", account_orders_path )  %></li>
						<li><%= link_to("登出", destroy_user_session_path, method: :delete ) %></li>
					</ul>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
	<!-- /.container-fluid -->
</nav>

<div id="spree-header" deluminate_imagetype="jpg">
	<header id="header" data-hook="">
		<div class="container navbar-default">
			<div class="row">
				<figure id="logo" class="col-md-4 col-sm-3" data-hook="">
					<a href="/"><img src="/assets/logo/spree_50-1c7335be355d4672a35c5023956d0c883f254831f3e3dae3f2ca05976ceb5e50.png" alt="Spree 50"></a>
				</figure>
				<nav class="navbar col-md-8 col-sm-9" id="top-nav-bar">
					<ul id="nav-bar" class="nav navbar-nav navbar-right" data-hook="">
						<script>
							if (typeof Spree.fetch_account !== 'undefined')
								Spree.fetch_account()
						</script>
						<li>
							<a href="/account">My Account</a>
						</li>
						<li>
							<a href="/logout">Logout</a>
						</li>
						<li id="search-bar" data-hook="">
							<form class="navbar-form" action="/products" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
								<div class="form-group">
									<select name="taxon" id="taxon" aria-label="Taxon" class="form-control">
										<option value="">All departments</option>
										<option value="1">Categories</option>
										<option value="2">Brand</option>
									</select>
								</div>
								<div class="form-group">
									<input type="search" name="keywords" id="keywords" placeholder="Search" class="form-control">
								</div>
								<input type="submit" value="Search" class="btn btn-success">
							</form>
						</li>
					</ul>
				</nav>

			</div>
		</div>
	</header>
	<div class="container">
		<nav class="col-md-12">
			<div id="main-nav-bar" class="navbar navbar-default">
				<ul class="nav navbar-nav navbar-brand" data-hook="">
					<li id="home-link" data-hook="">
						<a href="/">Home</a>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right" data-hook="">
					<li id="link-to-cart" data-hook="">
						<a class="cart-info empty" href="/cart">
							<span class="fa fa-shopping-cart"></span>
							Cart: (Empty)</a>
					</li>
					<script>
						Spree.fetch_cart()
					</script>
				</ul>
			</div>
		</nav>

	</div>
</div>

app/views/common/_side.html.erb
<h3 class="side-heading">Categories</h3>
<div class="list-group">
  <% cache Category.order('updated_at DESC').last do %>
    <% Category.find_each do |c| %>
      <%= link_to categories_products_path(category: c.name),class: "list-group-item" do %>
        <i class="fa fa-chevron-right"></i><%= c.name %>
      <% end %>
    <% end %>
  <% end %>
</div>
<!-- Categories Links Ends -->
<!-- Shopping Options Starts -->
<!-- <h3 class="side-heading">Shopping Options</h3> -->
<h3 class="side-heading">Brands</h3>
<div class="list-group">
  <!-- <div class="list-group-item">
    Brands
  </div> -->
  <% cache Brand.order('updated_at DESC').last do %>
    <% Brand.find_each do |b| %>
      <%= link_to brands_products_path(brand: b.name),class: "list-group-item" do %>
        <i class="fa fa-chevron-right"></i><%= b.name %>
      <% end %>
    <% end %>
  <% end %>
  <!-- <div class="list-group-item">
    <div class="filter-group">
      <label class="checkbox">
        <input name="filter1" type="checkbox" value="br1" checked="checked" />
        Brand Name 1
      </label>
    </div>
  </div> -->
  <!-- <div class="list-group-item">
    Manufacturer
  </div>
  <div class="list-group-item">
    <div class="filter-group">
      <label class="radio">
        <input name="filter-manuf" type="radio" value="mr1" checked="checked" />
        Manufacturer Name 1
      </label>
    </div>
  </div>
  <div class="list-group-item">
    <button type="button" class="btn btn-warning">Filter</button>
  </div> -->
</div>
<!-- Shopping Options Ends -->
<!-- Bestsellers Links Starts -->
<h3 class="side-heading">Most Popular</h3>
<div class="product-col side-product">
  <% Product.order("view_counts DESC").limit(1).each do |p| %>
    <div class="image">
      <%= link_to product_path(p) do %>
        <%= get_photo(p.photos) %>
      <% end %>
    </div>
    <div class="caption">
      <h4>
        <%= link_to(p.title ,product_path(p)) %>
      </h4>
      <div class="description">
        <%= p.description %>
      </div>
      <div class="price">
        <span class="price-new">$<%= discount_price(p.price) %></span>
        <span class="price-old">$<%= p.price %></span>
      </div>
      <div class="cart-button button-group">
        <% if p.quantity > 0 %>
          <%= button_to add_to_cart_product_path(p), :class => "btn btn-cart", :method=> :post do %>
            Add to cart<i class="fa fa-shopping-cart"></i>
          <% end %>
        <% else %>
          <p>已售完,補貨中</p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/common/_sidebar.html.erb
<!-- <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
  <% cache Category.order('updated_at DESC').last do %>
    <% Category.find_each do |c| %>
      <li>
        <%= link_to(c.name,products_path(category: c.name) )   %>
      </li>
    <% end %>
  <% end %>

      <%= search_form_for @q do |f| %>
        <li><%= f.label :標題或內文 %></li>
        <li><%= f.search_field :title_or_description_cont %></li>
        <li><%= f.submit '搜尋', :class => 'btn-search' %></li>
      <% end %>
</ul> -->

  <div class="w_sidebar">
    <section class="sky-form">
      <h4>Categories</h4>
      <div class="row1 scroll-pane">
        <div class="col col-4">
          <% cache Category.order('updated_at DESC').last do %>
            <% Category.find_each do |c| %>
              <label class="checkbox"><input type="checkbox" name="checkbox">
                <i></i><%= link_to(c.name,products_path(category: c.name) ) %>
              </label>
            <% end %>
          <% end %>
          <!-- <label class="checkbox"><input type="checkbox" name="checkbox" checked="">
            <i></i>Shoes</label> -->
        </div>
      </div>
    </section>
    <section class="sky-form">
      <h4>Brands</h4>
      <ul class="w_nav2">
        <% cache Brand.order('updated_at DESC').last do %>
          <% Brand.find_each do |b| %>
            <label class="checkbox"><input type="checkbox" name="checkbox">
              <i></i><%= link_to(b.name,products_path(brand: b.name) ) %>
            </label>
          <% end %>
        <% end %>
      </ul>
    </section>
    <section class="sky-form">
      <h4>search</h4>
        <ul class="w_nav2">
          <%= search_form_for @q do |f| %>
            <li><%= f.label :標題或內文 %></li>
            <li><%= f.search_field :title_or_description_cont %></li>
            <li><%= f.submit '搜尋', :class => 'btn btn-search' %></li>
          <% end %>
        </ul>
      </h4>
    </section>
  </div>